FROM ubuntu:16.04
MAINTAINER Fran Trapero Cerezo "frantracer@gmail.com"

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
RUN echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.4.list

RUN apt-get update && apt-get install -y --allow-unauthenticated mongodb-org

# Create the MongoDB data directory
RUN mkdir -p /data/db

# Initialize database
ADD ./mongodb/scripts/* /data/db/scripts/
RUN mongod --fork --logpath /var/log/mongodb.log --dbpath /data/db \
    && SCRIPT_FILES=/data/db/scripts/mongodb-deploy-*.js \
    && for script in $SCRIPT_FILES; do mongo $script; done \
    && mongod --shutdown

# Expose port 27017 from the container to the host
EXPOSE 27017

# Set usr/bin/mongod as the dockerized entry-point application
ENTRYPOINT ["/usr/bin/mongod"]